name:                idris-gambit
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/asandroq/idris-gambit#readme
license:             BSD3
author:              Alex Silva
maintainer:          asandroq@gmail.com
copyright:           Copyright (c) 2018 Alex Silva
category:            Compilers/Interpreters
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5 && < 1
  - idris >= 1.2.0 && < 2
  - transformers >= 0.5.2 && < 1

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - OverloadedStrings

executables:
  idris-codegen-gambit:
    source-dirs:      src
    main:             Main.hs
